source("https://bioconductor.org/biocLite.R")
biocLite(c("phyloseq", "metagenomeSeq"))
install.packages("devtools", repos='http://cran.revolutionanalytics.com/')
library(devtools)
install_github("epiviz/metavizr", dependencies=TRUE)
install.packages(c('getopt', 'reshape2', 'dplyr'))
